[package]
name = "urlshorten"
version = "0.1.0"
authors = ["EDJX <edjx@edjx.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
edjx = "0.1.0"
serde_json = "1.0"
serde = "1.0"
regex = "1"
